version: '3.8'

services:
  myblog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_ENV=development
    restart: unless-stopped